# -*- coding: utf-8 -*-
"""project_health_insurance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MGkgltWrVs7eoSitSIUHS-Om1WjJeUa
"""

import numpy as np
import pandas as pd
import pymc3 as pm
import matplotlib.pyplot as plt
import arviz as az
import daft
from google.colab.patches import cv2_imshow
import cv2

"""We will analyze full version of this dataset by using `BMI` ($BMI$), `children_count` ($CC$), `age` ($AGE$), `smoke` ($SM$),`region` ($RG$),  `sex` ($SX$), and `price` ($PC$) from this dataset. """

pgm = daft.PGM()
pgm.add_node("SM","SM",0,4)
pgm.add_node("SX","SX",0,2)
pgm.add_node("BMI","BMI",4,4)
pgm.add_node("AGE","AGE",2,2)
pgm.add_node("CC","CC",2,3)
pgm.add_node("RG","RG",4,1)
pgm.add_node("PC","PC",2,0)
pgm.add_edge("CC", "AGE")
pgm.add_edge("BMI", "CC")
pgm.add_edge("AGE", "PC")
pgm.add_edge("AGE", "RG")
pgm.add_edge("AGE", "SX")
pgm.add_edge("SM", "SX")
pgm.add_edge("CC","SM")
pgm.add_edge("SM", "PC")
pgm.add_edge("SX", "PC")
pgm.add_edge("RG", "PC")
pgm.add_edge("BMI","RG")
pgm.add_edge("BMI", "PC")
pgm.add_edge("BMI","SM")
pgm.render()
pgm.savefig("health-insurance-dag.jpg")

"""The above daft PGM does not work in google colab, so I took a snip of the DAG and printed it below. But on a regular jupyter notebook one can safely use it."""

img = cv2.imread('/content/health-insurance-dag.jpg')

cv2_imshow(img)

"""In our project, we are discussing whether gender and/or region have significant effect on the pricing of the health insurances. To be able to analyze this fully, one must analyze both first as individuals in a causal system, later on continue with a third step and adjust one of the $region$ or $sex$ to have a last idea on the case.

1) Here for to analyze the causal total and direct effect of the gender on the prices to analyze the gender effect, we should stratify the $age$ and $smoke$ parameters of people, but $smoker$ parameter should be coded to have a clear model.

2) We will measure the effect of the region total and direct again with similar method, but this time $BMI$ and $age$ should be stratified to have a better understanding of the effect.

3) As last part we will consider both parameters and that being said for the one that is adjusted we should add that parameter to the model to see full predictive model, and analyze the results.
"""

df = pd.read_csv('/content/insurance.csv')
df.head()

"""# Part A

Here we will stratify the hierarchical model for all of the given parameters for both $smoker$ and $age$.
"""

df["SM"] = pd.Categorical(df["smoker"]).codes

df["sx"] = pd.Categorical(df["sex"]).codes

df["ag"] = pd.Categorical(df["age"]).codes # age is not actually categorical, but can be thought as
# a cluster for each age.

# by that we can also visualize that effect too.

df.head()

"""Females are coded as 0, males are coded as 1. 
Smokers are coded as 1, non_smokers are coded as 0.
"""

df_A = df # to make each part easier for the user to understand.

pd.unique(df_A["ag"])

len(pd.unique(df_A["age"]))

"""The centered model with stratify intercept:
$$
\begin{align*}
G_i &\sim \text{Normal}(\mu_i, \sigma)
\\
\mu_i &= \alpha_{A[i]} + \beta_{S[i]} + \beta_{A[i]}
\\
\alpha_j &\sim \text{Normal}(\bar{\alpha}, \sigma_{\alpha}) \qquad \text{for} \ j \in 1..2 
\\
\beta_s &\sim \text{Normal}(0, 0.1) \qquad \text{for} \ a \in 1..2 
\\
\beta_a &\sim \text{Normal}(0, 0.01) \qquad \text{for} \ k \in 1..47 
\\
\bar{\alpha} &\sim \text{Normal}(0, 0.01)
\\
\sigma_{\alpha} &\sim \text{Exponential}(0.01)
\\
\sigma &\sim \text{Uniform}(0, 10)    
\end{align*}
$$
"""

def standardize(series):
    """Standardize a pandas series"""
    std_series = (series - series.mean()) / series.std()
    return std_series 

# thanks to Alaz hocam I could solve the model issue.

df_A["charges_std"] = standardize(df_A["charges"]) # to make the derivates non-zero.

with pm.Model() as mA:
    sigma = pm.Uniform("sigma", lower=0, upper=10)
    a_bar = pm.Normal("a_bar", 0, 0.01)
    sigma_A = pm.Exponential("sigma_A", 0.01)

    alpha_A = pm.Normal("alpha_A", mu=a_bar, sigma=sigma_A, shape=2)
    beta_S = pm.Normal("beta_S", mu=0, sigma=0.1, shape=2)
    beta_A = pm.Normal("beta_A", mu=0, sigma=0.01, shape=47)
    
    mu = alpha_A[df_A.sx.values-1] + beta_S[df_A.SM.values] + beta_A[df_A.ag.values]

    g = pm.Normal("G", mu=mu, sigma=sigma, observed=df_A.charges_std)
    
    trace_A = pm.sample(1000, tune = 1000, target_accept=0.95, init="adapt_diag", return_inferencedata = True )
az.summary(trace_A)

"""index 0 for beta_S is female and index 1 is male as coded.

Here from the results it is interesting to see that to the  female human having higher price rates for the health insurances, but relatively slightly with 0.004 mean difference, but we see that for male and female prices tend to increase regardless of gender. So gender has low effect on the increase of price, but female being on the negative side of the decrease of price trend comparably to males.

Furthermore, we see that after certain age, again higher index numbers at beta_A scores are increasing with age. so index 46 is actually the eldest person. To come back to main topic, we can say that after certain age which here is the index 25, something around 40-50 years old starts to change the trend for a health insurance company to change their pricing. After index 25 the prices start to have an increasing trend also due to age.

We also have the smoker parameter that is shown with beta_S that indicates that smoking highly effects the pricing of the health insurances. Beta_S=1 shows us that smokers tend to pay higher approx 0.9 mean when compared to Beta_S = 0 the mean of increase is -0.886.
"""

trace_A.keys() # to understand what are the keys to plot them.

_, ax = plt.subplots(1, 1, figsize=(6, 4))
az.plot_dist(trace_A.posterior["alpha_A"][:,0], ax=ax, color='y')
az.plot_dist(trace_A.posterior["alpha_A"][:,1], ax=ax, color='b')
ax.set_ylabel("density");

"""Here we will see gender differences both on posterior plot and trace, on the effect of pricing."""

az.plot_trace(trace_A, kind = "rank_bars", var_names=["alpha_A"], compact = False)

"""Here we will see effect of age on the pricing stratified at the gender based pricing analysis."""

az.plot_trace(trace_A, kind = "rank_bars", var_names=["beta_A"], compact = False)

"""Lastly, we will review smoker parameter $Beta_S$ for to see the effects."""

az.plot_trace(trace_A, kind = "rank_bars", var_names=["beta_S"], compact = False)

"""1) On the gender trace plot and the density plot we see slight inclination of the female gender to higher pricing. Moreover, we can clearly see from the values on the smoker parameters that smokers may not be seen inclined to increasing price trend however, when looked at the means below them it is evident that smoking skyrockets the health insurance prices.

2) We also see that $Age$ in a system with $smoker$ and $gender$ does not have that much of a statistically significant increasing effect on the prices.

# Part B

Here we will stratify the hierarchical model for all of the given parameters both for $bmi$ and $age$.
"""

df["rg"] = pd.Categorical(df["region"]).codes

df.head()

df_B = df # to make each part easier for the user to understand.

df_B["charges_std"] = standardize(df_B["charges"])
df_B["bmi_std"] = pd.Categorical(round(df_B["bmi"])).codes # think bmi as cluster
# fatter people will have different charges and can be thought as denser tanks.

len(pd.unique(df_B.bmi_std))

with pm.Model() as mB:
    sigma = pm.Uniform("sigma", lower=0, upper=10)
    rg_bar = pm.Normal("rg_bar", 0, 0.1)
    sigma_rg = pm.Exponential("sigma_rg", 0.1)

    alpha_rg = pm.Normal("alpha_rg", mu=rg_bar, sigma=sigma_rg, shape=4)
    beta_bmi = pm.Normal("beta_bmi", mu=0, sigma=0.1, shape = 36)
    beta_A = pm.Normal("beta_A", mu=0, sigma=0.1, shape=47)
    
    mu = alpha_rg[df_B.rg.values] + beta_bmi[df_B.bmi_std.values] + beta_A[df_A.ag.values]

    g = pm.Normal("G", mu=mu, sigma=sigma, observed=df_B.charges_std)
    
    trace_B = pm.sample(1000, tune = 1000, target_accept=0.95, init="adapt_diag", return_inferencedata = True )
az.summary(trace_B)

"""Here we see that for people who have higher BMI, indexes that are higher indicates higher BMI scores show that when people get fat price of the health insurance tend to increase but slightly, however since for the lower BMI it tends to lower the score, we can state that higher BMI has an effect when it combined with the region.

Specific regions have negative effect on the price decrease such as the $'Southeast'$ region has slightly higher prices, may be it is due to $'Southeast'$ being an industrial zone.
"""

_, ax = plt.subplots(1, 1, figsize=(6, 4))
az.plot_dist(trace_B.posterior["alpha_rg"][:,0], ax=ax, color='b')
az.plot_dist(trace_B.posterior["alpha_rg"][:,1], ax=ax, color='yellow')
az.plot_dist(trace_B.posterior["alpha_rg"][:,2], ax=ax, color='pink')
az.plot_dist(trace_B.posterior["alpha_rg"][:,3], ax=ax, color='orange')
ax.set_ylabel("density");

az.plot_trace(trace_B, kind = "rank_bars", var_names=["alpha_rg"], compact = False)

az.plot_trace(trace_B, kind = "rank_bars", var_names=["beta_bmi"], compact = False)

"""BMI based results in the region effect shows us that BMI increases the variance of the price, but does not contribute significantly on the increase or decrease of the pricing of health insurances.

"""

az.plot_trace(trace_B, kind = "rank_bars", var_names=["beta_A"], compact = False)

"""1) Here we see for the age parameter with $region$ considered model, we can say that young people tend to pay less due to decreasing price trend for young $age$ for the model.

2) We can also say that BMI increases the variability and $region$ certainly changes the pricing.

# Part C

Here we will stratify the hierarchical model for all of the given parameters below $sex$, $bmi$, and $age$.

To allocate memory and make the model, we reduced the observation size randomly without replace.

Also we want to expect to use a somewhat multivariate model to analyze the full system and later on compare the performances of $part A$, $part B$, $part C$, which will show us, which parameter contributes to the charges the most.
"""

df_C = df.sample(frac=0.05, replace = False)

df_C.index = np.arange(1, len(df_C)+1)

df_C["bmi_stand"] = standardize(df_C["bmi_std"])

df_C

"""Hierarchical multivariate model with sex and region combined with adjustment and exposure:

$$
\begin{align*}
G_i &\sim \text{Normal}(\mu_i, \sigma)
\\
\mu_i &= \bar{\alpha}_{rg[i]} +  \alpha_{A[i],S[i],BM[i]}
\\
\alpha &= (\text{diag}(\boldsymbol{S}_A) \boldsymbol{L}_A \boldsymbol{Z}_{T,A})^{T}
\\
\boldsymbol{Z}_{T,rg,A,S,BMI} &\sim \text{Normal}(0, 1) \qquad \text{for}
\ i,j,k \in  1..36, 1..30, 1..47
\\
\text{z}_{\bar{A},j} &\sim \text{Normal}(0, 1) \qquad \text{for} \ j \in 1..4
\\
\bar{\alpha} &= \text{z}_{\bar{A},j} \tau_A
\\
\boldsymbol{S}_{A}, \tau_A &\sim \text{Exponential}(1)
\\
\boldsymbol{R}_A &\sim \text{LKJcorr}(30,4)    
\end{align*}
$$
"""

with pm.Model() as mC:
    sigma_dist = pm.Exponential.dist(1.0)
    chol_actor, _, _= pm.LKJCholeskyCov("chol_actor", n = 30, eta = 4, sd_dist = sigma_dist, compute_corr = True)
    tau_A = pm.Exponential('tau_A', 1)
    z_A = pm.Normal("z_A", 0, 1, shape = 4)
    a_bar = z_A * tau_A
    z_actor = pm.Normal("z_actor", 0, 1, shape = (36,30,47))
    a = pm.math.dot(chol_actor, z_actor).T
    mu = a_bar[df_C.rg.values-1] + a[df_C.ag.values-1, df_C.sx.values-1,df_C.bmi_std.values-1]
    sigma = pm.Uniform("sigma", lower=0, upper=10)
    g = pm.Normal("G", mu=mu, sigma=sigma, observed=df_C.charges_std)
    trace_C = pm.sample(1000, tune = 1000, target_accept=0.95, init="adapt_diag", return_inferencedata = True )
    
az.summary(trace_C)

az.plot_trace(trace_C, kind = "rank_bars", var_names=["z_A"], compact = False)

"""Shows that second region has a tendency to have higher pricing for health insurance by the reasons only can be thought of such as industry, dirty air and so. z_A_1 directly shows that.

As from the summary above for Part_C which indicates a multivariate structure for $region$ effect when $sex$, $bmi$, and $age$ variables are stratified, which means included to be able to see the direct effect of the $region$, when other parameters observed and exposed are imposed to the model. 

1) From the page one with the 4 indexes of z_A we see that second region with index one has a positive effect on the pricing for the insurance companies, and that can be due to the site being an industrial zone or rich neighborhood, etc. 

2) from the z_actor parameter that is dependent on the age, gender, bmi and region shows us that for changing age, gender and bmi, there are no big changes in the pricing compared with the regional change.

3) By comparison of the three parts analyzed, we can state that $regional effect$ is critical on pricing health insurances. However, contrary to the belief of women have much more pricey health insurances are not seen that visible by the models created. This does not mean gender based pricing is negligible, however it indicates that for the data set used and for the prior model designed, it is seen that difference in pricing for different genders are not as much as statistically significant as $Region$ or $Smoker$.

4) Gender is indeed an important parameter on pricing, but not as much as smoking or region based on the dataset used and models created by the prior belief.

# Extra Part C

Here we will look at the chol_actor_corr parameter plot.
"""

from graphviz import Digraph
pm.model_to_graphviz(mC)

az.summary(trace_C.posterior.chol_actor_corr)

az.plot_trace(trace_C, kind = "rank_bars", var_names=["chol_actor_corr"], compact = False)

"""Here from the chol_actor_correlation we see that for the equal indexed cholesky covariance matrix correlations show significant underlying correlations are formed and put into the model."""